# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Travis Swicegood's Hugo Theme"
license = "MIT"
licenselink = "https://github.com/tswicegood/hugo-tswicegood-theme/blob/master/LICENSE.md"
description = "Personal theme for Travis Swicegood's blog"
homepage = "https://github.com/tswicegood/hugo-tswicegood-theme"
tags = ["website", "personal", "responsive", "blog", "Tachyons"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = 0.30.2

[author]
  name = "Travis Swicegood"
  homepage = "https://github.com/tswicegood"

[original]
  name = "Ananke Gohugo Theme"
  homepage = "https://github.com/budparr/gohugo-tswicegood-theme-ananke"
  repo = "//github.com/budparr/gohugo-tswicegood-theme-ananke"
